Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from IPython.display import display, clear_output
!pip install ipympl
clear_output()

%matplotlib inline
# %config InlineBackend.figure_formats = ['svg']
from ipywidgets import interact, interact_manual, FloatSlider
import numpy as np
import scipy
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, FFMpegFileWriter
import seaborn as sns
sns.set_style('darkgrid')
from sklearn.gaussian_process.kernels import RBF
from sklearn.gaussian_process.kernels import ConstantKernel

# sample training data
X = np.array([1.01, 3.51, 4.51, 7.01, 7.91, 9.01]).reshape(-1, 1)
Y = np.sin(X)
nb_steps = 200
delta_t = 10 / nb_steps
t = np.arange(0, total_time, delta_t)

@interact(l=FloatSlider(value=1., min=1e-5, max=3, step=0.1, continuous_update=False), 
          sigma2=FloatSlider(value=1., min=1e-5, max=10, step=0.1, continuous_update=False))
def anim_hyper(l, sigma2):
    kernel = ConstantKernel(constant_value=sigma2) * RBF(length_scale=l) 
    mean, cov = cond_distr(X, Y, t.reshape(-1, 1), kernel) 
    _plot(mean, cov)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_1768/2703967053.py[0m in [0;36m<module>[0;34m[0m
[1;32m     20[0m [0mnb_steps[0m [0;34m=[0m [0;36m200[0m[0;34m[0m[0;34m[0m[0m
[1;32m     21[0m [0mdelta_t[0m [0;34m=[0m [0;36m10[0m [0;34m/[0m [0mnb_steps[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 22[0;31m [0mt[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marange[0m[0;34m([0m[0;36m0[0m[0;34m,[0m [0mtotal_time[0m[0;34m,[0m [0mdelta_t[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     23[0m [0;34m[0m[0m
[1;32m     24[0m @interact(l=FloatSlider(value=1., min=1e-5, max=3, step=0.1, continuous_update=False), 

[0;31mNameError[0m: name 'total_time' is not defined
NameError: name 'total_time' is not defined

